package com.subsidian.emvcardmanager.enums

enum class ISOProcCode(val value: String) {
    TMK_DOWNLOAD_ISO_PROC_CODE("9A0000"),
    TSK_DOWNLOAD_ISO_PROC_CODE("9B0000"),
    TERM_PARAM_DOWNLOAD_ISO_PROC_CODE("9C0000"),
    CALL_HOME_ISO_PROC_CODE("9D0000"),
    CAPK_DOWNLOAD_ISO_PROC_CODE("9E0000"),
    AID_DOWNLOAD_ISO_PROC_CODE("9F0000"),
    TPK_DOWNLOAD_ISO_PROC_CODE("9G0000"),
    DAILY_REPORT_DOWNLOAD_ISO_PROC_CODE("9H0000"),
    IPEK_TRACK2_DOWNLOAD_ISO_PROC_CODE("9I0000"),
    IPEK_EMV_DOWNLOAD_ISO_PROC_CODE("9J0000"),
    SETTLEMENT_ISO_PROC_CODE("920000"),
    SETTLEMENT_BATCH_UPLOAD_CLOSE_ISO_PROC_CODE("960000"),
}