package com.subsidian.emvcardmanager.entities

data class ISOData(
    var primaryAccountNumber: String? = null,           //    2 Primary account number Mandatory
    var processingCode: String? = null,                 //    3 Processing code Mandatory
    var transactionAmount: String? = null,              //    4 Amount, transaction Mandatory
    var transmissionDateTime: String? = null,           //    7 Transmission date and time Conditional
    var settlementConversionRate: String? = null,       //    9 Conversion rate, settlement Conditional
    var systemTraceAuditNumber: String? = null,         //    11 Systems trace audit number Conditional
    var localTime: String? = null,                      //    12 Time, local transaction Mandatory
    var localDate: String? = null,                      //    13 Date, local transaction Conditional
    var expirationDate: String? = null,                 //    14 Date, expiration Conditional
    var settlementDate: String? = null,                 //    15 Date, Settlement Conditional
    var conversionDate: String? = null,                 //    16 Date, conversion Conditional
    var merchantType: String? = null,                   //    18 Merchant’s type Mandatory
    var posEntryMode: String? = null,                   //    22 POS entry mode Mandatory
    var cardSequenceNumber: String? = null,             //    23 Card sequence number Conditional
    var posConditionCode: String? = null,               //    25 POS condition code Mandatory
    var posPinCaptureCode: String? = null,              //    26 POS PIN capture code Conditional
    var transactionFeeAmount: String? = null,           //    28 Amount, transaction fee Conditional
    var settlementAmount: String? = null,               //    29 Amount, settlement fee Conditional
    var transactionProcessingFeeAmount: String? = null, //    30 Amount, transaction processing fee Conditional
    var settleProcessingFeeAmount: String? = null,      //    31 Amount, settle processing fee Conditional
    var acquiringInstitutionId: String? = null,         //    32 Acquiring institution id code Mandatory
    var forwardingInstitutionId: String? = null,        //    33 Forwarding institution id code Conditional
    var trackTwoData: String? = null,                   //    35 Track 2 data Conditional
    var retrievalReferenceNumber: String? = null,       //    37 Retrieval reference number Mandatory
    var authorizationIdResponse: String? = null,        //    38 Authorization id response Conditional
    var responseCode: String? = null,                   //    39 Response code Mandatory
    var serviceRestrictionCode: String? = null,         //    40 Service restriction code Conditional
    var cardAcceptorTerminalId: String? = null,         //    41 Card acceptor terminal id Optional
    var cardAcceptorIdCode: String? = null,             //    42 Card acceptor id code Conditional
    var cardAcceptorNameLocation: String? = null,       //    43 Card acceptor name/location Conditional
    var additionalResponseData: String? = null,         //    44 Additional response data Optional
    var additionalData: String? = null,                 //    48 Additional data Conditional
    var transactionCurrencyCode: String? = null,        //    49 Currency code, transaction Mandatory
    var settlementCurrencyCode: String? = null,         //    50 Currency code, settlement Conditional
    var pinData: String? = null,                        //    52 PIN data Conditional
    var securityRelatedControlInformation: String? = null,   //    53 Security related control information Conditional
    var additionalAmounts: String? = null,              //    54 Additional amounts Conditional
    var integratedCircuitCardData: String? = null,      //    55 Integrated Circuit Card System Related Data Conditional
    var messageReasonCode: String? = null,              //    56 Message reason code Optional
    var authorizingAgentId: String? = null,             //    58 Authorizing agent id code Conditional
    var transportEchoData: String? = null,              //    59 Transport (echo) data Conditional
    var paymentInformation: String? = null,             //    60 Payment Information Conditional
    var managementDataOnePrivate: String? = null,       //    62 Private, management data 1 Conditional
    var managementDataTwoPrivate: String? = null,       //    63 Private, management data 2 Conditional
    var primaryMessageHashValue: String? = null,        //    64 Primary Message Hash Value Conditional
    var extendedPaymentCode: String? = null,            //    67 Extended payment code Conditional
    var originalDataElement: String? = null,            //    90 Original data elements Mandatory
    var replacementAmount: String? = null,              //    95 Replacement Amounts Mandatory
    var payee: String? = null,                          //    98 Payee Conditional
    var receivingInstitutionId: String? = null,         //    100 Receiving Institution ID Code Optional
    var accountIdentification1: String? = null,         //    102 Account identification 1 Optional
    var accountIdentification2: String? = null,         //    103 Account identification 2 Optional
    var posDataCode: String? = null,                    //    123 POS data code Mandatory
    var nearFieldCommunicationData: String? = null,     //    124 Near Field Communication Data Conditional
    var secondaryMessageHashValue: String? = null,      //    128 Secondary Message Hash Value Mandatory
)
